/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

declare module "vue" {
  export interface GlobalComponents {
    AddExpenseForm: (typeof import("./components/AddExpenseForm.vue"))["default"];
    AddIncomeForm: (typeof import("./components/AddIncomeForm.vue"))["default"];
    AppFooter: (typeof import("./components/AppFooter.vue"))["default"];
    BalanceChart: (typeof import("./components/BalanceChart.vue"))["default"];
    DatetimePicker: (typeof import("./components/DatetimePicker.vue"))["default"];
    HelloWorld: (typeof import("./components/HelloWorld.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
  }
}
